kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build-production-image
    image: gradle:jdk16
    environment:
      DOCKERHUB:
        from_secret: dockerhub
    commands:
      - gradle jib --image=gigafyde/apollo:latest -Djib.to.auth.username=gigafyde -Djib.to.auth.password=$DOCKERHUB
    when:
      branch:
        - main
      event:
        - push

  - name: compile check
    image: gradle:jdk16
    commands:
      - gradle build
    when:
      branch:
        exclude:
          - main
