kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build-production-image
    image: gradle:jdk16
    environment:
      DOCKERHUB:
        from_secret: dockerhub
    commands:
      - gradle jib --image=gigafyde/apollo:latest -Djib.to.auth.username=gigafyde -Djib.to.auth.password=$DOCKERHUB
    when:
      branch:
        - production
        - main
      event:
        - push

  - name: compile check
    image: gradle:jdk16
    commands:
      - gradle build
    when:
      branch:
        exclude:
          - main
          - production

  - name: deploy
    image: razorpay/drone-kubernetes
    environment:
      KUBERNETES-TOKEN:
        from_secret: kubernetes-token
    kubernetes_server: https://192.168.1.200:6443
    kubernetes_token: $KUBERNETES-TOKEN
    namespace: default
    deployment: apollo
    repo: gigafyde/apollo
    container: apollo
    tag: latest
    when:
      branch:
        - production
      event:
        - push
