kind: pipeline
type: docker
name: arm

platform:
  arch: arm64

steps:
  - name: compile
    image: 'openjdk:11-jdk-slim-buster'
    commands:
      - 'chmod +x ./gradlew'
      - './gradlew shadowJar --no-daemon'

  - name: docker-build
    image: plugins/docker
    settings:
      repo: gigafyde/apollo
      username: gigafyde
      password:
        from_secret: dockerhub
      tags: latest
      force_tag: true
