kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: arm64

steps:
  - name: build-production-image
    image: arm64v8/openjdk:11
    environment:
      DOCKERHUB:
        from_secret: dockerhub
    commands:
      - ./gradlew jib --image=gigafyde/apollo:latest -Djib.to.auth.username=gigafyde -Djib.to.auth.password=$DOCKERHUB
    when:
      branch:
        - main
