kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build-production-image
    image: gradle:jdk18
    environment:
      GITHUB:
        from_secret: github-token
    commands:
      - chmod +x gradlew
      - ./gradlew jib --image=ghcr.io/phazorworks/apollo:latest -Djib.to.auth.username=gigafyde -Djib.to.auth.password=$GITHUB
    when:
      branch:
        - production
        - main
      event:
        - push

  - name: compile check
    image: gradle:jdk18
    commands:
      - gradle build
    when:
      branch:
        exclude:
          - main
          - production
